version: '3.8'
services:
  dns:
    build: ./
    command: go run ./network/dns/dns_server.go
    networks:
      bankwifi:
        ipv4_address: 10.38.8.2
  http:
    build: ./
    command: go run ./network/http/http_server.go
    networks:
      bankwifi:
        ipv4_address: 10.38.8.3
  client:
    build: ./
    volumes:
      - ${HOST_PROJECT_DIR}/intercepted_files:/files
      - ${HOST_PROJECT_DIR}:/workspace/project3
    depends_on:
      - "dns"
      - "http"
    command: [/bin/sh, -c, "tcpdump -i any -U -w /workspace/project3/mitm.pcap & go run ./mitm & sleep 5 && go run ./network/client/client.go & wait"]
    networks:
      bankwifi:
        ipv4_address: 10.38.8.4

networks:
  bankwifi:
    ipam:
      config:
        - subnet: "10.38.8.0/24"
